<?php

/**
 * Her implementeres hook_node_view().
 * Tilføjer Facebook-share knappen ved hjælp af facebook-add funktionen
 * 
 */
function facebook_node_view($node, $view_mode, $langcode)
{
  $node->content['facebook'] = array(
    '#markup' => theme('facebook_add_share_button'),
  );
}

/**
 * Implementerer hook_theme() - fortæller Drupal om vores theme-funktion.
 */
function facebook_theme()
{
  return array(
    'facebook_add_share_button' => array('variables' => NULL),
  );
}

/**
 * Denne funktion tilføjer Facebook-share knappen
 */
function theme_facebook_add_share_button()
{
  $output = '<a name ="fb_share" type="button"></a> <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>';
 
  return $output;
}


?>